"""add is_frozen to accounts

Revision ID: 27742b821c5c
Revises: eb89600ef132
Create Date: 2026-09-06 15:07:40.322294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27742b821c5c'
down_revision: Union[str, Sequence[str], None] = 'eb89600ef132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_frozen', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_frozen')
    # ### end Alembic commands ###
